### ISSUE TITLE
EC2 Image Builder support for container images

### ISSUE THREAD

**Issue by rlwalker927** [aws-samples/amazon-ec2-image-builder-samples#11]
Hi,

I recently contributed an artifact to AWS internally and wanted to contribute a modified version of it to this repo since I used the other samples here as a reference for my own. I have created a PR that adds a README, template, and JSON parameters file to a new directory I created as part of the CloudFormation directory. I tried to model my README and CloudFormation template the same as the others for simplicity. Additionally, my component document uses a very basic example that mimics the AWS Documentation. I would be more than happy to modify this into something more advanced like the .NET example for Ubuntu. Let me know if you have any additional questions or potential modifications to improve. If you don't feel that my contributions would be of value in this repo that's ok but figured I would check anyways!

**Comment by tpaulus** [comment]
Merged PR. Thanks for the submission!
