### ISSUE TITLE
Missing Sub function for IAM role ARN in template.yml

### ISSUE THREAD

**Issue by awserik** [aws-samples/amazon-ec2-image-builder-samples#13]
[Line 27](https://github.com/aws-samples/amazon-ec2-image-builder-samples/blob/master/lambda/latest_image_tracker/template.yml#L27) includes ${AWS::Partition} in the ARN of the Lambda IAM role but the line does not include the Sub CFN function which results in an error when deploying the template:

Error:

```
ARN arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole is not valid. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: InvalidInput; Request ID: 5ad74aa9-c2b3-47be-9894-e164bdaad468; Proxy: null)
```

**Comment by tpaulus** [comment]
Fixed!
