### ISSUE TITLE
TargetECRRepositoryName does not exist in CloudFormation Template

### ISSUE THREAD

**Issue by mosulcoder** [aws-samples/amazon-ec2-image-builder-samples#18]
Getting error message "An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [TargetECRRepositoryName] do not exist in the template" when executing the create-stack CLI command. Issue appears to be incorrect parameter name in the parameters file.

**Comment by austoonz** [comment]
Thank you for filing this issue.
Can I can which CloudFormation template you were trying to deploy when you ran into this error?

**Comment by austoonz** [comment]
Resolved in https://github.com/aws-samples/amazon-ec2-image-builder-samples/pull/19.
Thank you!
