### ISSUE TITLE
Use url suffix pseudo parameter instead of ec2.amazonaws.com

### ISSUE THREAD

**Issue by EmmanuelTsouris** [aws-samples/amazon-ec2-image-builder-samples#28]
https://github.com/aws-samples/amazon-ec2-image-builder-samples/blob/48dda6e958488f023d77384ccddce2c003cbd942/CloudFormation/Linux/ubuntu-with-net6/ubuntuserver20-with-.net6.yml#L51

Use url suffix pseudo parameter instead of hard coding ec2.amazonaws.com, to ensure compatibility with other AWS partitions which may use a different suffix.

`- !Sub "ec2.${AWS::URLSuffix}"`

**Comment by austoonz** [comment]
Pushed [this commit](https://github.com/aws-samples/amazon-ec2-image-builder-samples/commit/c49d4d6f3e78a0ad5ff65d2a65c27dfe1d608473) to resolve this.
