### ISSUE TITLE
Documentation on when to use ImageBuilder Pipelines

### ISSUE THREAD

**Issue by sholtomaud** [aws-samples/amazon-ec2-image-builder-samples#37]
There is no recommendations on when or when not to use Pipelines. 

EG the Cfn example doesn't have a pipeline while the CDK does. 

Why? And when should we chose either of these two options?

**Comment by sholtomaud** [comment]
Not really. I mean, it just sounds random rather than reasoned, like "we are showing you how to do a 1 off ami with this Cfn. You would typically only do this for testing" etc etc

**Comment by austoonz** [comment]
This repository's purpose is provide samples that customers can use to learn more about ways to interact with, or create Image Builder resources. It is not intended to be a source of truth for the best practices on how each individual or business should model their golden image workflows.

Given that, the note that "this repository is aimed at testing purposes" is the accurate take.

For more focused best practice guidance I would look towards AWS blog posts such as [Automate OS Image Build Pipelines with EC2 Image Builder](https://aws.amazon.com/blogs/aws/automate-os-image-build-pipelines-with-ec2-image-builder/) or [Create immutable servers using EC2 Image Builder and AWS CodePipeline](https://aws.amazon.com/blogs/mt/create-immutable-servers-using-ec2-image-builder-aws-codepipeline/) (I'm sure there are others, they were the first two I found).
