### ISSUE TITLE
Latest Image tracker sample fails to deploy

### ISSUE THREAD

**Issue by PilotBob** [aws-samples/amazon-ec2-image-builder-samples#38]
I have tracked this down to:

https://github.com/aws-samples/amazon-ec2-image-builder-samples/blob/ec5afc10342f8761fa51b64e46503e5a39677eb0/lambda/latest_image_tracker/template.yml#L34

Changed to:
```
Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
```             
 To resolve error.

**Comment by austoonz** [comment]
Closing. This was resolved in https://github.com/aws-samples/amazon-ec2-image-builder-samples/pull/39.
