### ISSUE TITLE
a couple of typos

### ISSUE THREAD

**Issue by mh-macginitie** [aws-samples/amazon-ec2-image-builder-samples#53]
- DelectionPolicy instead of DeletionPolicy in windows-baseline-stack.yml
- "EC2 ]instance" (stray ] character) in README.md in CloudFormation/Windows/windows-server-with-latest-ssm-agent

**Comment by austoonz** [comment]
Thank you for reporting these (even if we are very late to resolving them!).

Resolved in https://github.com/aws-samples/amazon-ec2-image-builder-samples/commit/73cc7b818ebe44ac342f60f2d40e5c3843f584f7.
